---
image: debian:12

variables:
  GIT_DEPTH: 0
  SSL_CERT_FILE: "./go.pem"
  SSL_CERT_DIR: "/path/does/not/exist/to/pin/ca"

stages:
  - build
  - test

before_script:
  # Prepare packages
  - apt-get update
  - apt-get -y dist-upgrade
  - apt-get -y install ca-certificates git golang make
  # Configure signing key
  - echo 'dev-personal-git@iodine ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOaK5/rx1e5OSInMYOwoLeGyIwi7Hpao0qUC4oyO0/Wr' >"${HOME}/.signers"
  # Verify repo and checkout the correct ref
  - git -c gpg.ssh.allowedSignersFile="${HOME}/.signers" verify-commit HEAD
  - git checkout -B "$CI_COMMIT_REF_NAME"
  - git -c gpg.ssh.allowedSignersFile="${HOME}/.signers" verify-commit HEAD

build-job:
  stage: build
  script:
    - go mod tidy
    - go mod verify
    - git diff go.mod go.sum
    - sha256sum --strict --check go.pin
    - go env -w GOPROXY=off GOFLAGS='-mod=readonly -trimpath'
    - go generate ./...
    - go build -o "build/${CI_PROJECT_NAME}"
    - go env -w GOPROXY=off GOFLAGS='-mod=readonly -trimpath -buildmode=pie -ldflags=-s -w'
    - GOFER_RELEASE=true go generate ./...
    - GOOS=darwin GOARCH=arm64 go build -o "build/release/${CI_PROJECT_NAME}-darwin-arm64"
    - GOOS=linux GOARCH=amd64 go build -o "build/release/${CI_PROJECT_NAME}-linux-amd64"
    - GOOS=linux GOARCH=arm64 go build -o "build/release/${CI_PROJECT_NAME}-linux-arm64"
    - GOOS=windows GOARCH=amd64 go build -o "build/release/${CI_PROJECT_NAME}-windows-amd64"
    - find build ! -type d ! -name SHA256SUMS -exec sha256sum --tag '{}' \; >build/SHA256SUMS
    - cat build/SHA256SUMS |sort
  variables:
    LC_ALL: "C"
    TZ: "UTC"
  artifacts:
    paths:
      - ./build
    expire_in: 1 week

test-job:
  stage: test
  script:
    # Clone, verify and build gofer
    - oldwd="$(pwd)"
    - git clone https://github.com/illikainen/gofer "${HOME}/gofer"
    - cd "${HOME}/gofer"
    - git -c gpg.ssh.allowedSignersFile="${HOME}/.signers" verify-commit HEAD
    - make tidy
    - make verify
    - make
    - mv build/gofer-linux-amd64 /usr/local/bin/gofer
    - cd "$oldwd"
    # Run the tests
    - make tidy
    - make
    - make check
    - make test
