#!/usr/sbin/nft -f

flush ruleset

table inet orch_filter {
    chain input {
        type filter hook input priority -3000; policy {{ .Policy.Ingress }};
        ct state invalid drop

        {{- range $r := .IngressRules }}
        {{ $r }}
        {{- end }}
    }

    chain forward {
        type filter hook forward priority -3000; policy {{ .Policy.Forward }};
        ct state invalid drop

        {{- range $r := .ForwardRules }}
        {{ $r }}
        {{- end }}
    }

    chain output {
        type filter hook output priority -3000; policy {{ .Policy.Egress }};
        ct state invalid drop

        {{- range $r := .EgressRules }}
        {{ $r }}
        {{- end }}
    }
}

table ip orch_nat {
    chain prerouting {
        type nat hook prerouting priority 0
        ct state invalid drop
    }

    chain input {
        type nat hook input priority 0
        ct state invalid drop
    }

    chain postrouting {
        type nat hook postrouting priority 0
        ct state invalid drop

        {{- range $r := .PostroutingRules }}
        {{ $r }}
        {{- end }}
    }

    chain output {
        type nat hook output priority 0
        ct state invalid drop
    }
}

include "/etc/nftables.d/*.nft"
