name: Pipeline

on: [push, pull_request]

jobs:
  pipeline:
    runs-on: ubuntu-latest
    container:
      image: debian:12
    steps:
      - name: Prepare signing key
        run: |
          echo 'dev-personal-git@iodine ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOaK5/rx1e5OSInMYOwoLeGyIwi7Hpao0qUC4oyO0/Wr' >"${HOME}/.signers"

      - name: Prepare packages
        run: |
          apt-get update
          apt-get -y dist-upgrade
          apt-get -y install ca-certificates git golang make

      - name: Checkout gofer
        uses: actions/checkout@v4
        with:
          path: gofer
          repository: illikainen/gofer
          fetch-depth: 0

      - name: Build gofer
        run: |
          chown -R root:root .
          git -c gpg.ssh.allowedSignersFile="${HOME}/.signers" verify-commit HEAD
          make tidy
          make verify
          make
          cp build/gofer-linux-amd64 /usr/local/bin/gofer
        working-directory: gofer

      - name: Checkout ourself
        uses: actions/checkout@v4
        with:
          path: this
          fetch-depth: 0

      - name: Build ourself
        run: |
          chown -R root:root .
          git -c gpg.ssh.allowedSignersFile="${HOME}/.signers" verify-commit HEAD
          make tidy
          make verify
          make
          make release
          find build ! -type d ! -name SHA256SUMS -exec sha256sum --tag '{}' \; >build/SHA256SUMS
          cat build/SHA256SUMS |sort
        working-directory: this

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: ./this/build

      - name: Test
        run: |
          make check
          make test
        working-directory: this
