name: Pipeline

on:
  push:
    branches:
      - master
    pull_request:
      - master

jobs:
  pipeline:
    runs-on: ubuntu-latest
    container:
      image: debian:12
    steps:
      - name: Prepare packages
        run: |
          set -ex
          apt-get update
          apt-get -y dist-upgrade
          apt-get -y install ca-certificates git golang make
      - name: Checkout gofer
        uses: actions/checkout@v4
        with:
          path: gofer
          repository: illikainen/gofer
          fetch-depth: 0
      - name: Build gofer
        run: |
          set -ex
          chown -R root:root .
          make tidy
          make
          cp build/gofer-linux-amd64 /usr/local/bin/gofer
        working-directory: gofer
      - name: Checkout ourselves
        uses: actions/checkout@v4
        with:
          path: this
          fetch-depth: 0
      - name: Build
        run: |
          set -ex
          chown -R root:root .
          make tidy
          make
          make release
          find build ! -type d ! -name SHA256SUMS -exec sha256sum '{}' \; >build/SHA256SUMS
          cat build/SHA256SUMS
        working-directory: this
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: ./this/build
      - name: Lint
        run: make check
        working-directory: this
